apiVersion: v1
kind: Service
metadata:
  name: overengineered-service
spec:
  type: LoadBalancer
  selector:
    app: overengineered
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080