
- name: Enable container features
  replace:
    path: /boot/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
  - "cgroup_enable=cpuset"
  - "cgroup_memory=1"
  - "cgroup_enable=memory"
  become: yes
  register: cgroup 

- name: Reboot to apply changes
  reboot:
  when: cgroup.changed
  become: yes

- name: Try to run k3s command 
  command: k3s
  register: k3s_test

- name: Determine whether k3s is installed
  set_fact:
    k3s:
      is_installed: "{{ ('command not found' in k3s_test.stdout) | ternary(false, true) }}"

- name: Install k3s
  shell: curl -sfL https://get.k3s.io | sh - 
  when: not k3s.is_installed
