- name: Install PyYAML
  pip:
    name: pyyaml
    executable: pip3

- name: Enable container features
  replace:
    path: /boot/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
  - "cgroup_enable=cpuset"
  - "cgroup_memory=1"
  - "cgroup_enable=memory"
  become: yes
  register: cgroup 

- name: Reboot to apply changes
  reboot:
  when: cgroup.changed
  become: yes

- name: Check if k3s is installed
  is_installed:
    name: k3s
  register: k3s

- name: Install k3s
  shell: curl -sfL https://get.k3s.io | sh - 
  when: not k3s.is_installed

- name: Check if Helm is installed
  is_installed:
    name: helm
  register: helm

- name: Install Helm
  shell: |
    mkdir -p ~/install/helm
    cd ~/install/helm
    wget https://get.helm.sh/helm-v3.13.0-linux-arm64.tar.gz
    tar -zxvf helm-v3.13.0-linux-arm64.tar.gz
    mv linux-arm64/helm /usr/local/bin/helm
  become: yes
  when: not helm.is_installed